crossfit/urls.py
from django.urls import path

from . import views


app_name = "crossfit"

urlpatterns = [
    #path('', views.FilteredDesignedComponentListView.as_view(), name='overview'),
    path("wod_<int:pk>/", views.workout_detail, name="workout-detail"),
    path("wod_add/", views.add_workout, name="workout-add"),
    path("excercise_add/", views.add_excercise, name="excercise-add"),
]

fitness/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("main/", include("main.urls")),
    path("crossfit/", include("crossfit.urls")),
]

main/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

crossfit/models.py
from datetime import datetime

from django.db import models
from django.contrib.auth.models import User

from main.models import Location


class Excercise(models.Model):
    name = models.CharField(max_length=200)


class ExcerciseDetails(models.Model):
    """
    The definition of an excercise as defined in a Workout or performed in a Session.
    """
    excercise = models.ForeignKey(Excercise, on_delete=models.PROTECT)
    magnitude = models.DecimalField(max_digits=8, decimal_places=2)
    repetitions = models.PositiveIntegerField(blank=True, null=True)

    TYPES = [
        ("D", "distance"),
        ("R", "repetitions"),
    ]
    type = models.CharField(max_length=1, choices=TYPES, default="R")

    UNITS = [
        ("K", "kg"),
        ("L", "lb"),
        ("M", "m"),
        ("N", ""),
    ]
    unit = models.CharField(max_length=1, choices=UNITS, default="N")


class Workout(models.Model):
    """
    A workout definition.
    """
    name = models.CharField(max_length=200)
    excercises = models.ManyToManyField(ExcerciseDetails)
    WORKOUT_TYPES = [
        ("A", "AMRAP"),
        ("T", "for time"),
        ("M", "max"),
    ]
    type = models.CharField(max_length=1, choices=WORKOUT_TYPES, default="T")


class Session(models.Model):
    """
    A performed workout session.
    Excercises are copied from a workout definition to allow changing default values.
    """
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    workout = models.ForeignKey(Workout, on_delete=models.PROTECT)
    excercises = models.ManyToManyField(ExcerciseDetails)
    datetime = models.DateTimeField(default=datetime.now)
    location = models.ForeignKey(Location, on_delete=models.PROTECT)

main/models.py
from django.db import models


class Location(models.Model):
    city = models.CharField(max_length=200)
    name = models.CharField(max_length=200)

    LOC_TYPES = [
        ("G", "gym"),
        ("A", "area"),
    ]
    type = models.CharField(max_length=1, choices=LOC_TYPES, default="A")

crossfit/forms.py
from django import forms

from crispy_forms.layout import Layout, ButtonHolder, Submit, Div, Field, Row, Column
from crispy_forms.bootstrap import InlineCheckboxes, PrependedText
from crispy_forms.helper import FormHelper

from .models import *


class WorkoutForm(forms.ModelForm):
    helper = FormHelper()

    helper.layout = Layout(
        Row(
            Div(
                "name",
                "type",
                css_class="col",
            ),
        )
    )

    class Meta:
        model = Workout
        fields = [
            "name",
            "type",
        ]


class ExcerciseDetailForm(forms.ModelForm):
    helper = FormHelper()

    helper.layout = Layout(
        Row(
            Div(
                "excercise",
                "magnitude",
                "repetitions",
                css_class="col",
            ),
        )
    )

    class Meta:
        model = ExcerciseDetails
        fields = [
            "excercise",
            "magnitude",
            "repetitions",
        ]


class ExcerciseForm(forms.ModelForm):
    helper = FormHelper()

    helper.layout = Layout(
        Row(
            Div(
                "name",
                css_class="col",
            ),
        )
    )

    helper.add_input(Submit('submit', 'Submit', css_class='btn-primary'))

    class Meta:
        model = Workout
        fields = [
            "name",
        ]

crossfit/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.forms import formset_factory

from .models import *
from .forms import *


def index(request):
    return HttpResponse("Hello, world. You're at the polls index.")


def workout_detail(request, pk):
    details = get_object_or_404(Workout, pk=pk)

    context = {
        "details": details,
    }

    return render(request, 'crossfit/workout.html', context)


def add_workout(request):
    form = WorkoutForm(request.POST or None)
    FormSet = formset_factory(form=ExcerciseDetailForm, extra=6)
    formset = FormSet()

    if request.method == "POST":
        if form.is_valid():
            contact = form.save()

            return redirect("crossfit:workout-detail", pk=pk)

    context = {
        "form": form,
        "formset": formset,
    }

    return render(request, "crossfit/workout_form.html", context)


def add_excercise(request):
    form = ExcerciseForm(request.POST or None)

    if request.method == "POST":
        if form.is_valid():
            contact = form.save()

            return redirect("crossfit:workout-detail", pk=pk)

    context = {
        "form": form,
    }

    return render(request, "crossfit/generic_form.html", context)

main/views.py
from django.shortcuts import render
from django.http import HttpResponse


def index(request):
    return render(request, 'main/index.html')

crossfit/templates/crossfit/generic_form.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block app_title %}
    {{ block.super }}
    Supplier - add
{% endblock %}


{% block content %}
<div class="card-body">
    <div class="col-lg-8">
        {% crispy form %}
    </div>
</div>
{% endblock content %}

crossfit/templates/crossfit/workout.html
{% extends 'main/base.html' %}
{% load static %}


{% block content %}

hei

{% endblock content %}

crossfit/templates/crossfit/workout_form.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block app_title %}
    {{ block.super }}
    Supplier - add
{% endblock %}


{% block content %}
<div class="card-body">
    <div class="col-lg-8">
        <form method="post" enctype="multipart/form-data" action=".">
            {% crispy form %}
            {% for ex_form in formset %}
                {{ forloop.counter }}
                {% crispy ex_form %}
                <hr>
            {% endfor %}
        <input type="submit" name="submit" value="Save" class="btn btn-primary btn-success"
             id="submit-id-submit">
        </form>
    </div>
</div>
{% endblock content %}

main/templates/main/base.html
<!DOCTYPE html>
<html>
<head>

  <meta content="text/html;charset=utf-8" http-equiv="Content-Type">
  <meta content="utf-8" http-equiv="encoding">

  <title>Fitness</title>

	<!-- JQuery -->
	<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

  <!-- Bootstrap -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

  <!-- Font awesome -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
	<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js" integrity="sha512-RXf+QSDCUQs5uwRKaDoXt55jygZZm2V++WUZduaU/Ui/9EGp3f/2KZVahFZBKGH0s774sd3HmrhUy+SgOFQLVQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

	{% block styles %}
	{% endblock styles %}

	{% block header %}
	{% endblock header %}


</head>
<body>

{% block content %}
{% endblock %}

</body>
</html>

main/templates/main/index.html
{% extends 'main/base.html' %}
{% load static %}


{% block content %}

<div class="Row">
    <div class="mb-4 px-2">
        <a href="{% url 'crossfit:workout-add' %}" class="btn btn-primary rounded-0">Add workout</a>
    </div>
    <div class="mb-4 px-2">
        <a href="{% url 'crossfit:excercise-add' %}" class="btn btn-primary rounded-0">Add excercise</a>
    </div>
</div>


{% endblock content %}